services:
  tsugijs:
    build: ./
    container_name: tsugijs

  nginx1:
    image: nginx:stable-alpine
    container_name: nginx1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - tsugijs
